### ISSUE TITLE
Images grid carousel

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#38]
Extension of #24. Upon clicking an image in the images grid, a [modal window will appear with a carousel](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=3514-6008&mode=dev).

**Comment by shirin27** [comment]
- Caption, description are the same in lightbox and grid
- There is only one lightbox defined, no matter which image you click, that displays all the images in the grid plus extra ones defined in the document
- Would there be an indicator for the user that the assets are clickable?

**Comment by DanielaPedrochevd** [comment]
Agile Requirement: 

As a user, when I click on any image from the [gallery block](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-156647&mode=dev), a [modal window will appear with a carousel](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=3514-6008&mode=dev) and I can navigate through it. 

Description: 

Extend https://github.com/Netcentric/vg-macktrucks-com-rd/issues/24. so that when a user clicks on an image from the gallery a lightbox is opened displaying a carousel of images through which they can navigate. 

Acceptance Criteria: 

1. When the user clicks on the image, a lightbox that follows the design in figma for [mobile](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=3514-6097&mode=dev) and [desktop](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=3514-6008&mode=dev) opens displaying all the images in the grid plus extra ones, these images can have text descriptions. 
2. As a user on desktop, I can navigate through the images using the left and right arrows. 
3. As a user on a mobile/tablet I can navigate through the images swiping my fingers. 
4. To close the lightbox on desktop I can either use the "x" button or the "esc" key or click outside the lightbox (dark background). 
5. To close the lightbox on mobile/tablet I can either use the "x" button or touch the dark background.

**Comment by DanielaPedrochevd** [comment]
@BeckyMedlin Can you please answer these questions? 

1. We don't have a tablet design/measurements for this functionality or many others, how have we been handling this until now? 
2. Do you want any kind of indicator on hover on the [gallery images](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-156647&mode=dev) to indicate these are clickable to the end-user?

**Comment by BeckyMedlin** [comment]
@ZoeBeykirch Please see questions above and advise.

**Comment by WendyKruger** [comment]
@DanielaPedrochevd 

1. We have asked the dev team to use their best judgement on whether to use mobile or desktop design/measurements for the functionalities, and bring it up in the review meetings if unsure
2. Can we have a hover effect like on the trucks gallery here:  https://www.macktrucks.com/trucks/ - so raise up and get a big bigger

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
 as tested on https://38-images-grid-carousel--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/tdziezyk/v2/images-grid-with-modal
