### ISSUE TITLE
Hero variant for Solutions page

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#45]
On certain pages we have a so-called [secondary hero](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=478-26373&mode=design&t=cVDpihR7kqOneqkM-4).

Make the font in the Header secondary variant white instead of black.

Tertiary Hero Design:
<img src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/139977780/c2db5f5c-8c0e-4b4b-b245-e140a6ae18e3" width="100%">

**Comment by DanielaPedrochevd** [comment]
**Agile Requirement**

As a business owner, I want to achieve the following design, so that I can use this secondary variant hero in the pages that I want. 

**Description**

Make the font in the Header secondary variant white instead of black.

**Acceptance Criteria**

- The font in the Header secondary variant is white instead of black.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results.  hence, marking the issue to 'Bugs Done'.
Below outstanding observations are now fixed and revalidated as passed.

**Secondary Hero:**     Margin after Title Text “ Mack Highway”    Expected: 24px ; Actual: 41px :    Fixed now 

**Tertiary Hero:** Margin after Title Text “ Mack Highway”     Actual: 41px.: Fixed now 

Text pixel size is 600px X 48px as expected Except for Light version where can see first line as 600X24. :  Fixed now
