### ISSUE TITLE
Card variant for solutions

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#87]
https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2220-93083&mode=dev

Variant of cards, showing title/text + 2 cards

**Comment by BeckyMedlin** [comment]
Please add to next sprint @Gonzalo-CG This needs to be part of MVP.

**Comment by DanielaPedrochevd** [comment]
**Agile Requirement** 
As a business owner I want to display the following [figma design ](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2220%3A93083&mode=dev)

**Description** 
Develop a new "Solutions" variant of the [Cards Block ](https://github.com/orgs/Netcentric/projects/2/views/3?filterQuery=card&pane=issue&itemId=35940510) so that it displays a Title, a text and a button next to 2 cards as per the above-mentioned design. 

**Acceptance Criteria** 

1. There's a new "Solutions" variant available for the cards block that follows the figma design.

**Comment by DanielaPedrochevd** [comment]
duplicate #63
